### ISSUE TITLE
few problems regarding new ships

### ISSUE THREAD

**Issue by Javran** [Vultren/k2badge#2]
for keeping track of https://github.com/KC3Kai/KC3Kai/pull/1862#issuecomment-283663025

- all Winter 2017 ship appear only in en
- Iku and Nimu are grouped together in non-ens but in en they are still separated

also some problem in Poster Collection related to remodel chain:

- Fujinami Kai doesn't seem to toggle Fujinami on (same problem goes with Asakaze Kai, Matsukaze Kai, Zara Due, I-13 Kai, I14 Kai)
- Saratoga icon not toggled on

**Comment by Nya-chan** [comment]
Ad remodel chain - it seems I have missed updating conversion.json file on the server, will update it ASAP, should fix the behaviour.

**Comment by Nya-chan** [comment]
Update: remodel chain issues should be fixed, conversion uploaded

**Comment by Vultren** [comment]
everything should be fixed so closing
